anchors:
  setup-node: &setup-node
    run:
      name: Setup node
      command: |
        curl -sL https://deb.nodesource.com/setup_12.x |  bash -
        apt update && apt-get -q -y install nodejs

  configure-build-environment: &configure-build-environment
    run:
      name: Configure
      command: |
        sed "s/GITHUB_TOKEN/$GITHUB_AUTH_TOKEN/g" .nuget.config > nuget.config
        npm install .

version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    steps:
      - *setup-node
      - checkout
      - *configure-build-environment
      - run:
          name: Compile
          command: npm run gulp Build
      - run:
          name: Run Tests
          working_directory: .
          command: npm run gulp Test
      - store_test_results:
          path: ./TestResults
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    steps:
      - *setup-node
      - checkout
      - *configure-build-environment
      - run:
          name: Push
          command: |
            echo "setting up git config"
#            git config user.email "bot@xerris.com"
#            git config user.name "Xerris-bot"
            echo "pushing new version to NUGET"
            file=version.json
            echo $CIRCLE_TAG >> $file
            echo " Tag: " + $CIRCLE_TAG
#            npm run gulp Push
#            echo "comitting version.json change to git"
#            git add version.json
#            git commit -m "committing change to version.json"
#            git push origin main

workflows:
  version: 2
  ci-main:
    jobs:
      - build:
          context: xerris-core
          filters:
            branches:
              only:
                - main
      - deploy:
          context: xerris-core
          filters:
            branches:
              only:
                - main
  ci-deploy:
    jobs:
      - deploy:
          context: xerris-core
          filters:
            tags:
              only:
                - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              ignore: /.*/
