name: Publish My Project

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/build-and-publish-nuget
    with:
      csproj-path: './src/Xerris.DotNet.Core/Xerris.DotNet.Core.csproj'