name: Publish My Project

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/build-and-publish-to-nuget.yml
    with:
      csproj-path: './src/Xerris.DotNet.Core/Xerris.DotNet.Core.csproj'
      nuget-package-name: 'xerris.dotnet.core'
      nuget-api-key: secrets.NUGET_API_KEY
      nuget-source-uri: secrets.NUGET_SOURCE_URI