name: Publish My Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-and-publish-to-nuget.yml
    with:
      csproj-path: './src/Xerris.DotNet.Core/Xerris.DotNet.Core.csproj'
      nuget-package-name: 'xerris.dotnet.core'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE_URI: ${{ secrets.NUGET_SOURCE_URI }}      