name: Publish My Project

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/build-and-publish-nuget.yml
    with:
      csproj-path: './src/Xerris.DotNet.Core/Xerris.DotNet.Core.csproj'
      nuget-package-name: 'xerris.dotnet.core'