name: Increment Version on Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_and_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run build
        run: |
          # Add your build commands here
          echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build_and_checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Add your test commands here
          echo "Running tests..."

  add_production_tag:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Add New Production Tag Script
        run: |
          chmod +x .github/workflows/add-new-production-tag.sh
          ./.github/workflows/add-new-production-tag.sh